### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by heyfolk** [Santeeisweird9/discord-economy-bot#9]
When I try to run the bot getting this error 
![Screenshot_20220220-134218_Chrome](https://user-images.githubusercontent.com/60790859/154834296-4aae794a-6116-43b3-81fd-e37c2d7504a3.png)

**Comment by CantisW** [comment]
What is your node version (check with `node --version`)? I can't yet reproduce this issue.

**Comment by heyfolk** [comment]
Node v16

**Comment by CantisW** [comment]
How are you running the bot? It should be ran with `npm start` (make sure to run `npm i` first).
Does this occur when you start the bot or during runtime?

Edit: After some further digging, the way JSONs are imported here doesn't work on versions below `v16.14.0`. Can you try updating to the latest node version and trying again?

**Comment by heyfolk** [comment]
Yes when i start the bot it gives error Starting through node. index.js and node version is latest

**Comment by heyfolk** [comment]
I upgrade node and it worked with node v17. Ty for help
